SAP/python-pyodata

setup.py

This change is for switching from internal SAP PyPi to packaging on oficial PyPi.org

Update setup.py for PyPi

---

pyodata/client.py

I didn't expect that metadata will be sent in anything else that ASCII.
But we absolutely need to know the charset because of labels.
Northwind returns "Content-Type: application/xml;charset=utf-8"
Closes #7

client: correctly detect MIME

---

pyodata/v2/model.py
pyodata/v2/service.py
tests/conftest.py
tests/test_model_v2.py

In the metadata document, it is allowed to declare same Entity Sets in
different ends of one Association Set. Therefore, we cannot utilize
dictionary to store such ends (values can be overwritten).
In this commit, there is added a new class AssociationSetEndRole which
represents one end within the Association Set. End roles are stored in
a list, in the same manner like end roles in the Association. Also,
each end now contains a reference to a corresponding entity set.

Handle association set ends with same entity sets

---

setup.py

pypi now reject other then .rst description without specifying content type. 
More info: https://pypi.org/help/#description-content-type

setup.py - add long_description_content_type

---

pyodata/v2/model.py
tests/test_model_v2.py

Edm.Int64 should have the suffix L
SucessFactors services return some values without the suffix L

model: fix parsing of Edm.Int64 values

---

pyodata/v2/model.py
pyodata/v2/service.py
tests/metadata.xml
tests/test_model_v2.py
tests/test_service_v2.py

OData V2 FunctionImports do no have to have ReturnType defined:
https://help.sap.com/viewer/u_collaboration_dev_help/dacad2174f654e62a75754d71fee9da2.html#loiodacad2174f654e62a75754d71fee9da2__FunctionImport

No return type functions

---

docs/index.rst
docs/usage/README.md
docs/usage/deleting.rst
pyodata/v2/service.py
tests/test_service_v2.py

We never realized that delete entity function has been missing until
issue 54 was created. Hence this commit which adds that functionality to
our lib.
All added code is tested and 'How to use delete function' was also added
to the documentation.
resolves #54

Add delete entity function

---

pyodata/v2/model.py
pyodata/v2/service.py

1) Lines 837, 844, 851, 873, 896, 915, 948 in model.py has been affected
by new rule "Unnecessary use of a comprehension". Rationale for the
changes can be found here: https://github.com/PyCQA/pylint/issues/2905
2) Line 84 in service.py has been affected by new rule "Unnecessary
"else" after "break"". In our case exiting if block is granted
by brake statement, therefore else is not necessary

Update code to incorporate new rules in pylint

---

.travis.yml

Since we provide pyodata as library and lxml is unpinned dependency, we should check at least major stable releases of lxml. Travis-CI has limit 200 concurrent jobs for open source, currently we use 3x8=24 combinations of python and lxml versions.

update travis.yml - check multiple lxml version

---

CHANGELOG.md
pyodata/v2/model.py
tests/metadata.xml
tests/test_model_v2.py

**Changes:**
- Consistent way of parsing 'Nullable' bool attributes
- Supports 'Nullable' attribute for properties (default: True)
- Supports 'Nullable' attribute for function import parameters (default: False)
Fixes #98

Correct parsing of 'Nullable' attributes

---

CHANGELOG.md
pyodata/v2/service.py
tests/test_service_v2.py

In the case where we need to update several entity sets,
we probably don't want to specify HTTP method for each of them.
This patch does nothing but enhances user convenience.

service: add service wide configuration

---

.pylintrc

This is a quick fix for issue #130. Rules should be enabled with respective code refactoring.

Update .pylintrc - disable new check from 2.6.0

---

CHANGELOG.md
pyodata/v2/model.py
tests/test_client.py
tests/test_model_v2.py

Consider this an idea thrown away. If OK, there should definitely be added more tests for various invalid metadata files parsed and checked for expected result, but at the moment is IMHO enough just modifying existing test cases. 
Rationale for new property:
Policies Fatal, Warning a Ignore are modifying the behavior in a way that following is not possible to do (create simple validator)
1)	Go trough entire metadata for having all problems logged (exceptions thrown) - Fatal stops on first error
2)	Some kind of information that there are real problem in metadata - Warning will go to the end, but mix warning messages (unsupported annotation etc.) with real metadata parsing problem (various exceptions). Parsing logger is possible but ugly.
3)	Policies as they are so far are actually useful …

add new property is_valid for Schema class

---

dev-requirements.txt

Builds for PRs are failing with linter checks unrelated to the PR itself, when also upgrade of package happens. This is not convenient for anyone wanting to fix something.

Fix versions of linters

---

.pylintrc
pyodata/client.py
pyodata/v2/model.py
pyodata/v2/service.py
pyodata/vendor/SAP.py
tests/test_client.py
tests/test_service_v2.py
tests/test_vendor_microsoft.py

Because we have minimal Python version listed as 3.6, we can safely move to PEP 498 -- Literal String Interpolation.
f-strings are less verbose, more powerful (it is expression, e.g. can call functions) and quicker than old school string formatters. 
Converted using https://github.com/ikamensh/flynt

chore: %-formatting to f-string

---

pyodata/v2/model.py
tests/test_model_v2.py

This closes #143
- Adds constant `FIX_SCREWED_UP_MINIMAL_DATETIME_VALUE` to return 0001-01-01
- Adds constant `FIX_SCREWED_UP_MAXIMUM_DATETIME_VALUE` to return 9999-12-31
- Add new unittests

Workaround for screwed up date values

---

CHANGELOG.md
docs/usage/vendors.rst
pyodata/vendor/SAP.py
tests/test_vendor_sap.py

solves #109, rewritten to helper as requested in #158
@jfilak , I think functionality-wise this is finished (including tests); I could add some docs but not sure what would be best location - does it make sense to put them in initialization, or best to make a new, separate, top-level section `vendors.rst`?
also a comment for the implementation: `add_btp_token_to_session()` requires the session object to be given as argument, instead of creating it inside - this allows to avoid adding a `requests` dependency. so the intended usage is something like this:
```python
session = SAP.add_btp_token_to_session(requests.Session(), KEY, USER, PASSWORD)
client = pyodata.Client(SERVICE_URL, session)
```

vendors: token helper for SAP BTP, ABAP env service

---

.reuse/dep5
LICENSES/Apache-2.0.txt
README.md

Passing locally
```
(v) c:\github-com-actual\python-pyodata>reuse lint
* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: Apache-2.0
* Read errors: 0
* Files with copyright information: 50 / 50
* Files with license information: 50 / 50
Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)
```
Closes #171 #170 #169

add files for REUSE compliance

---

pyodata/v2/service.py
tests/test_service_v2.py

Some special URL characters (such as `+`, `=` and `&`) were not escaped in query parameters. This would introduce a risk of data corruption or URL injection.
Note: I did not notice any breakage when testing against SAP. However, I only tested a few use cases (e.g., I barely tested batched requests).

Always escape special chars in URL query params

---

.travis.yml

Update compatibility matrix with new LXML and Python releases

chore:  Update .travis.yml - Add Python 3.10 and latest LXML

---

CHANGELOG.md
pyodata/v2/model.py
tests/test_model_v2.py

model: split properties schema.entity_types/complex_types and their generated Collections 
Changed:
- data from  Schema.entity_sets are now in Schema.complex_types and Schema._collections_entity_sets 
- data from  Schema.complex_types are now in Schema.complex_types and Schema._collections_complex_types --
- update tests to better cover generated Collections inside schema parsing
Additional details:
- class Types is still containing both types and their generated collection variant, since it is static class for odata primitive types
Long explanation: 
Collections of entity types were added with focus of "get function imports working", which is main use case of pyodata. See commit 009198379 for details.
For use case of metadata validation, it is however not API user friendly to return two, …

model: split collections in Schema class

---

CHANGELOG.md
pyodata/v2/model.py
tests/metadata.xml
tests/test_model_v2.py

If the `edmx` Schema of the Database contains empty attributes / empty strings, see updated `metadata.xml:339`, e,g.,
`<Property Name="Material_Type" Type="Edm.String" sap:text="" />`,
then `pyodata` throws an error:
`RuntimeError: The attribute sap:text of StructTypeProperty(Material_Type) is set to non existing Property `.
This fix accounts for empty attribute values, together with unit tests to test the behavior.

fix: more robust handling of XML EntityType Property with empty attributes

---

CHANGELOG.md
pyodata/v2/model.py
tests/test_service_v2.py

Default value was broken in several ways:
- Month 0 does not exist
- Day 0 does not exist
- Year 0 can not be handled by Python datetime
The new default value is copied from Edm.DateTime for consistency reasons. However, choosing something less common like 1.1.1 or 1.1.1970 might be more sensible?

model: fix default Edm.DateTimeOffset value (#195)

---

CHANGELOG.md
docs/usage/initialization.rst
pyodata/client.py
pyodata/v2/model.py
pyodata/v2/service.py
tests/test_service_v2.py

Until now, null values received from a OData server get substituted by a
default value.
Users of this library can not tell apart a value which coincidentally
equals the default, and a missing (null-ed) value received from the
server.
This commit allows the user to disable the substitution of null values by
default values, retrieving a None object instead.
Questions:
- Is this an acceptable approach to implement this features?
<s>In case the maintainers agree with the direction, I will add tests and documentation.</s> (done)

service: Support null (#79)

---

pyodata/v2/service.py
tests/test_service_v2.py

Reading the spec, using the __next field, not $top/$skip/__count seems
to be the pristine way of fetching an entity collection in full:
> In response payloads, representing Collections of Entries, if the
> server does not include an object for every Entry in the Collection of
> Entries identified by the request URI then the response represents a
> partial listings of the Collection. In this case, "__next" name/value
> pair is included to indicate the response represents a partial
> listing. The value of the name/value pair is a URI which identifies
> the next partial set of entities from the originally identified
> complete set.
However, I am not sure if this the right way to implement this functionality. Feedback greatly appreciated.
Main question:
- What are the reasons that this …

service: Support for server-side pagination (partial listings)

---

CHANGELOG.md
pyodata/v2/model.py
tests/metadata.xml
tests/test_model_v2.py
tests/test_model_v2_EdmStructTypeSerializer.py
tests/test_model_v2_VariableDeclaration.py

Could not find any documentation on the default value if missing, but it seems is quite obvious that false, as opposed to true, is the only reasonable choice.
Please note: I have not defaulted the new parameter `fixed_length` in the `StructTypeProperty` constructor, because I got the impression that this class is not really meant to be part of the public API. Please let me know if you think otherwise.

model: Extract property 'FixedLength'

---

docs/usage/querying.rst

A simple NameError when executing 'Get entities matching a filter' code. Instead of 'smith_employees', it should be 'smith_employees_request'.

docs: fix a NameError in querying.rst

---

pyodata/v2/service.py
tests/metadata.xml
tests/test_model_v2.py
tests/test_service_v2.py

When playing around with the [OData API of the SAP Analytics Cloud](https://api.sap.com/api/Story_API/resource) to retrieve some stories, I have noticed that the nav method did not work with many to one relationships. The SAC API specifies such an relationship between a story and users (createdByUser, a story can be created only by one user, but a user can create many stories): Either you have to specify a key for the nav method or to use the get_entities method which both not works as the target entity is not a list of entities (the entity is returned directly and not in a results array) or as an invalid url is generated (the target entity is being indexed, which does not work as it is not an list).
I have tracked down this issue down to line …

service: fix navigation for associations with many to one relationships and for associations with relationships to same entity

---

CHANGELOG.md
pyodata/v2/model.py
tests/test_model_v2.py

We were expecting that the offset part is mandatory and that the service should return /Date(1659430517461+0000)/ for offset set to UTC. Unable confirm in odata.org and W3C specifications, but some services (SAP included) works for this Edm type as if offset is not mandatory for the UTC timezone.
Now, if the offset part is missing in incoming JSON payload, it should work as if +0000 was provided.
FIXES #231

model: fix edge case for Edm.DateTimeOffset.from_json() without offset

---

.github/workflows/python-linters.yml

Bump to latest stable bugfix version of Py3.10 
PR jobs did not run for a long time and 3.10.1 image is no longer available for "platform_version": "22.04",

ci: use python 3.10.10 for linter job

---

CHANGELOG.md
docs/usage/deleting.rst
docs/usage/querying.rst
docs/usage/updating.rst
pyodata/v2/service.py
tests/test_service_v2.py

Sometimes services expect the path to be percent encoded. This can especially be important 
when special variable types are key fields like Date type, where a ':' will appear in the path. 
In this case you can use an optional parameter to make the request encode the path.
Per default the variable encode_path is set to False.

Encode path option get and update

---

tests/test_service_v2.py

- remove remove test_function_import_without_return_type_wrong_code
The entire logic of the test was based on scenario that server returns response of HTTP 204 No Content (which ends with HTTP Header) with some content in HTTP Body, which is breaking the HTTP protocol logic itself.
The Responses package generated such weird simulated response and was parsed with urllib 1.X in previous versions of Requests, but now, with being compatible with urllib3 2.x, breaking changes were introduced within this transitive dependency.
On the requests side, the bump to same urllib3 2.x means test failures with error:
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(10 bytes read, -10 more expected)', IncompleteRead(10 bytes read, -10 more expected))
- test_update_entity
Same …

tests: fix failures from bump of transitive deps to urllib3 2.X

---

pyodata/v2/service.py
tests/test_service_v2.py

EntityProxy expected expanded properties to be wrapped in a 'results' object, which isn't to V2 JSON spec. This fix removes this expectation. The original behavior is not removed, so if there happens to be an expanded property wrapped in a 'results' object, EntityProxy continues to work as before.
Fixes #258

Fix adding expanded entities to EntityProxy

---

.github/workflows/python-tests-compatibility.yml

Because CI for package compatibility are a intentionally a "moving target" for package updates, it is not enough to depend on running just after commit to master.
When long time pass, build is often broken due compatibility changes irrelevant to actual code change. So this change is intended to at least spot problems before such situation and ease debugging of CI.

ci: setup compatibility runs also weekly

---

dev-requirements.txt

- bump bandit to latest that support python 3.7 
- set version for sphinx

chore: bumps in dev-requirements.txt

---

pyodata/v2/model.py

Adding two missing possibilities for `ValueListParameter` from from the [SAP common vocabulary list](https://sap.github.io/odata-vocabularies/vocabularies/Common.html)

Adding two missing possibilities for ValueListParameter
